[phases.setup]
nixPkgs = ["nodejs_20"]
nixLibs = []

[phases.install]
cmds = ["cd frontend && npm install"]

[phases.build]
cmds = ["cd frontend && npm run build"]

[start]
cmd = "cd frontend && ./node_modules/.bin/serve dist -l $PORT"
